
export const recipes = [
    {
        id: "r1",
        name: "Spaghetti",
        description: "Delicious spaghetti with tomato sauce",
        ingredients: [{ ingredient: "Spaghetti", quantity: "500g" }, { ingredient: "Tomato Sauce", quantity: "300g" }],
        steps: ["Boil spaghetti", "Put sauce on spaghetti", "Enjoy!"],
        category: "pasta",
        time: "20 min",
        author: "Max",
        uid: "u1",
        date: "2022-01-01",
    },
    {
        id: "r2",
        name: "Lasagna",
        description: "Homemade lasagna with meat sauce",
        ingredients: [{ ingredient: "Meat", quantity: "500g" }, { ingredient: "Tomato Sauce", quantity: "300g" }],
        steps: ["Boil meat", "Put sauce on meat", "Enjoy!"],
        category: "pasta",
        time: "30 min",
        author: "Max",
        uid: "u1",
        date: "2022-01-01",
    },
    {
        id: "r3",
        name: "Risotto",
        description: "Risotto with chicken and vegetables",
        ingredients: [{ ingredient: "Risotto", quantity: "500g" }, { ingredient: "Tomato Sauce", quantity: "300g" }, { ingredient: "Chicken", quantity: "500g" }, { ingredient: "Vegetables", quantity: "500g" }],
        steps: ["Boil risotto", "Heat oil in pan", "Put sauce on risotto", "Enjoy!"],
        category: "pasta",
        time: "40 min",
        author: "Julie",
        uid: "u3",
        date: "2022-11-01",
    },
    {
        id: "r4",
        name: "Pizza",
        description: "Pizza with tomato sauce and cheese",
        ingredients: [{ ingredient: "Tomato Sauce", quantity: "300g" }, { ingredient: "Cheese", quantity: "100g" }],
        steps: ["Boil tomato sauce", "Put cheese on tomato sauce", "Enjoy!"],
        category: "pizza",
        time: "10 min",
        author: "Manuel",
        uid: "u2",
        date: "2022-03-11",
    },
    {
        id: "r5",
        name: "Hamburger",
        description: "Hamburger with cheese and bacon",
        ingredients: [{ ingredient: "Bacon", quantity: "500g" }, { ingredient: "Cheese", quantity: "100g" }],
        steps: ["Boil bacon", "Put cheese on bacon", "Enjoy!"],
        category: "pizza",
        time: "15 min",
        author: "Dumplin",
        uid: "u11",
        date: "2022-03-11",
    },
    {
        id: "r6",
        name: "Salad",
        description: "Salad with tomato sauce and cheese",
        ingredients: [{ ingredient: "Tomato Sauce", quantity: "300g" }, { ingredient: "Cheese", quantity: "100g" }],
        steps: ["Boil tomato sauce", "Put cheese on tomato sauce", "Enjoy!"],
        category: "salad",
        time: "10 min",
        author: "Manuel",
        uid: "u2",
        date: "2022-03-11",
    },
    {
        id: "r7",
        name: "Soup",
        description: "Soup with tomato sauce and cheese",
        ingredients: [{ ingredient: "Tomato Sauce", quantity: "300g" }, { ingredient: "Cheese", quantity: "100g" }],
        steps: ["Boil tomato sauce", "Put cheese on tomato sauce", "Enjoy!"],
        category: "soup",
        time: "10 min",
        author: "Manuel",
        uid: "u2",
        date: "2022-03-12",
    },
    {
        id: "r8",
        name: "Tater Tot Casserole",
        description: "Tater tot casserole with cheese",
        ingredients: [{ ingredient: "Hamburger", quantity: "1lb" }, { ingredient: "Cheese", quantity: "100g" }, { ingredient: "Tater Tots (frozen)", quantity: "1 bag" }, { ingredient: "Cream of Mushroom Soup", quantity: "2 cans" }, { ingredient: "Sour Cream", quantity: "1/4 cup" }],
        steps: ["Preheat oven to 375°F", "Put tater tots on baking sheet and place in oven while it heats up and you prepare other ingredients", "Brown Hamburger", "Salt and pepper to taste", "Stir in soup until thoroughly mixed", "Stir in sour cream", "Pour into oven safe dish with extra room to add tots", "Add layer of shredded cheese", "remove from oven and add tater tots on top of cheese layer", "Add a little seasoned salt and some more cheese on top of tots", "Bake for about 30 minutes",  "Enjoy!"],
        category: "casserole",
        time: "45 min",
        author: "Dumplin",
        uid: "u11",
        date: "2022-03-12",
    },
    {
        id: "r9",
        name: "Taco Soup",
        description: "Taco soup with cheese",
        ingredients: [{ ingredient: "Hamburger", quantity: "1 lb" }, { ingredient: "Cheese", quantity: "1 cup" }, { ingredient: "Black Beans", quantity: "1 can" }, { ingredient: "Sour Cream", quantity: "1/4 cup" }, { ingredient: "Red Beans", quantity: "1 can" }, { ingredient: "Green Chiles", quantity: "1 can" }, { ingredient: "Tortilla Chips", quantity: "1 bag" }, { ingredient: "Tomato Soup", quantity: "1 can" }, { ingredient: "Diced Tomatoes", quantity: "1 can" }, { ingredient: "Hominy", quantity: "1 can" }, { ingredient: "Taco Seasoning", quantity: "1/4 cup" }, {ingredient: "Diced Onion", quantity: "2 Tbsp"}, { ingredient: "Water", quantity: "1 can" }, { ingredient: "Sour Cream", quantity: "to taste" }, { ingredient: "Diced Jalepenos", quantity: "to taste" }],
        steps: ["In 5qt saucepan add Hominy and water, begin to heat on medium", "Heat pan over medium heat, add hamburger", "While hamburger browns, add other ingredients to soup mixture", "Once hamburger is brown, drain and add to soup", "Reduce heat slightly and let simmer for 10-15 minutes", "Add portion to bowl, add shredded cheese, sour cream, and jalepenos to your liking", "Serve with tortilla chips", "Enjoy!"],
        category: "soup",
        time: "25 min",
        author: "Manuel",
        uid: "u2",
        date: "2022-03-12",
    }
]